spring:
  datasource:
    jdbcUrl: jdbc:log4jdbc:mariadb://61.75.35.56:3306/t1?serverTimezone=asia/seoul
    username: glovis-user
    password: ishift7150!
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 10
      poolName: pool01

  jpa:
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      # ddl-auto: none
      ddl-auto: update

  profiles:
    active: none

jwt:
  header: Authorization
  secret:
    key: C&F)J@NcRfUjXn2r5u8x/A?D*G-KaPdS


server:
  port: 35063

logging:
  config: classpath:logback-spring.xml
